// <auto-generated />
namespace GamePool2016.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PlayerPoolGame_PointsEarned : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayerPoolGame_PointsEarned));
        
        string IMigrationMetadata.Id
        {
            get { return "201611280028084_PlayerPoolGame_PointsEarned"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
